BoringUtils: rwprobe from inside module, test.
chipsalliance/chisel pull request #3485
Opened 2023-08-12 00:05 UTC by dtzSiFive

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- Backend code generation
- Bugfix

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference).

#### Release Notes

RWTaps are done from inside the module instead of externally, for compatibility.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels? (Select the most appropriate one based on the "Type of Improvement")
- [ ] Did you mark the proper milestone (Bug fix: `3.5.x`, `3.6.x`, or `5.x` depending on impact, API modification or big change: `6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

2023-08-14 18:56 UTC, dtzSiFive commented
Small change to get rwTaps of IO's working.

Can see it in action across an Interface here: https://github.com/dtzSiFive/chisel3/commit/3db4be901af27c793b48567bc6ceb6008ab3b7cc (unfortunately Verilator's "lint" complains about forcing to an input port).

Don't feel strongly, but perhaps all probes should work this way, so ensure a read-only and writable tap to same "thing" behave the same.

2023-08-21 20:39 UTC, debs-sifive approved these changes

2023-08-21 20:41 UTC, debs-sifive requested changes
actually, can you create a new test case for, e.g.
```scala
it should "work when tapping IO"
```

and also demonstrate what happens when you try to tap an IO that fails the case that you put in for
```scala
        case (rhs, (module, _))
            if (up && module == path(0) && isPort(rhs) && (!createProbe.nonEmpty || !createProbe.get.writable)) => {
```

2023-08-21 23:49 UTC, debs-sifive approved these changes
thanks for the changes!

2023-08-22 01:34 UTC, merged